### ISSUE TITLE
The data loading may show undefined behaviors, if users change the stored data manually.

### ISSUE THREAD

**Issue by Ch40gRv1-Mu** [AY2122S2-CS2113T-T10-3/tp#136]
such that it's possible lead to flaw if user tries to modify the data files manually.

**Comment by chooyikai** [comment]
Adding to this issue. Currently we have already fixed the bug that allows registration of duplicate modules if you manually edit the JSON file, but I just realised that the modules' MCs are not validated (in the program, only 0-100 are allowed) so you can input negative MCs or MCs which are too big.
