### ISSUE TITLE
[PE-D] There are no examples in the command summary 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2113T-T10-3/tp#138]
It may be a hassle for users who do not want to read the whole UG and just wants to know all implementation
![Pic B.JPG](https://raw.githubusercontent.com/wraineflores/ped/main/files/62bebff8-008c-4bf5-a987-4ed4c726434f.JPG)

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: wraineflores/ped#2

**Comment by chooyikai** [comment]
Resolved by #173 (although the formatting is currently broken, I will fix it in the next PR).
