### ISSUE TITLE
[PE-D] Error message not displayed

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2113T-T10-3/tp#141]
This is not user friendly, I think a message should be displayed to show what exactly the error is about so the user can correct it.
![150cce30910be4418ceb122a59687d72.png](https://raw.githubusercontent.com/suenalaba/ped/main/files/9296797d-8cb0-4e16-a12f-1c1625bb95d9.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: suenalaba/ped#2

**Comment by Ch40gRv1-Mu** [comment]
See [Issue #165](https://github.com/AY2122S2-CS2113T-T10-3/tp/issues/165#issue-1189950413)
