### ISSUE TITLE
[PE-D] Error message not shown correctly for del task

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2113T-T10-3/tp#143]
Error message should display "Please enter a valid index", instead of just displaying the exception shown.

![bed3981d28d333553a9b5a9edaabb4c4.png](https://raw.githubusercontent.com/suenalaba/ped/main/files/49839a55-52a1-4788-acfc-711789f898b5.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: suenalaba/ped#3

**Comment by Ch40gRv1-Mu** [comment]
See [issue #165](https://github.com/AY2122S2-CS2113T-T10-3/tp/issues/165#issue-1189950413)
