### ISSUE TITLE
[PE-D] Errors thrown for grade when using grade function

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2113T-T10-3/tp#146]
![Pic C.JPG](https://raw.githubusercontent.com/wraineflores/ped/main/files/ee4cbc25-8381-4da8-9836-376dc298678a.JPG)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: wraineflores/ped#3

**Comment by Ch40gRv1-Mu** [comment]
This works well from my side, and I guess the possible reason is that the test typed in 2 extra "\n". If so, may modify the ModHappyParser to void the empty "\n".
<img width="519" alt="Screen Shot 2022-04-03 at 11 45 25 AM" src="https://user-images.githubusercontent.com/78465180/161410420-cd6069f9-1dc7-4053-881d-ec71b7fe21d4.png">

**Comment by chooyikai** [comment]
Unable to reproduce
