### ISSUE TITLE
[PE-D] Duplicate tasks

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2113T-T10-3/tp#152]
Exactly the same task with same duration allowed to be added, I think this shouldn't be the case? 

![729537e88c984ab410eee95c256e9684.png](https://raw.githubusercontent.com/suenalaba/ped/main/files/7b48f6c2-d7d1-4026-afe1-3413d43baea2.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: suenalaba/ped#7

**Comment by Ch40gRv1-Mu** [comment]
Actually, I think this should be allowed? Our future user story contains the recursive task, where the tasks may have the same description but distinct durations.(e.g. some tutorial may be shorter than normal)

**Comment by chooyikai** [comment]
Yes, this is intended behaviour
