### ISSUE TITLE
[PE-D] Cosmetic bug when editing non-existent task

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2113T-T10-3/tp#165]
**Describe the bug**

Editing a zero-indexed task prints a IndexOutOfBoundsException message. (Does not crash)

**To Reproduce**

1. Type `edit task 20-0 -n "asd"`, make sure task 200 doesn't exist

**Expected behavior**

A more graceful message informing the user of the error, instead of only IndexOutOfboundsException

Screenshots

![image.png](https://raw.githubusercontent.com/IncompetentDev/ped/main/files/eca09c11-e87a-4d97-8006-680f7ef617e6.png)

-------------
Labels: `type.FunctionalityBug` `severity.VeryLow`
original: IncompetentDev/ped#5

**Comment by Ch40gRv1-Mu** [comment]
The bug come from the un-catched exception in editTaskFromModule in EditCommand.
<img width="1362" alt="Screen Shot 2022-04-03 at 11 11 15 AM" src="https://user-images.githubusercontent.com/78465180/161409669-b2906897-b981-4332-80cc-61d3020f0040.png">
https://github.com/AY2122S2-CS2113T-T10-3/tp/blob/15a7dfad694b94f1061725932c4a88a6e4112bab/src/main/java/seedu/duke/commands/EditCommand.java#L115-L138
I think we should check other part of the code also. Especially the part that calls external/java functions and make sure all of them all in try...catch loop.
